apiVersion: v2
name: bookkeeper
description: Bookkeeper Helm chart for Kubernetes
version: 0.7.0
appVersion: 0.7.0
keywords:
  - log storage
  - stream storage
home: https://github.com/apache/bookkeeper
icon: https://bookkeeper.apache.org/images/bookkeeper_logo_blk.png
