apiVersion: v2
name: bookkeeper-operator
description: Bookkeeper Operator Helm chart for Kubernetes
version: 0.1.0
keywords:
  - log storage
  - stream storage
home: https://github.com/pravega/bookkeeper-operator
icon: https://bookkeeper.apache.org/images/bookkeeper_logo_blk.png
