## Default values for bookkeeper-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper-operator
  tag: 0.1.6-76-2908ab4
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: bookkeeper-operator

## Whether to create the CRD.
crd:
  create: true

testmode:
  enabled: false
  ## version is used to specify the major version number
  ## of the unreleased bookkeeper version that you wish to deploy
  ## or provide an upgrade path to
  ## Note: mention the major version number
  ## eg. enter 0.8.3 if u wish to deploy version 0.8.3-2500.efe501a
  version: ""
  ## fromVersion is used to specify the major version number
  ## of the unreleased bookkeeper version you wish to provide an upgrade path from
  ## i.e. if you wish to provide an upgrade path from this unreleased version (testmode.fromVersion)
  ## to the unreleased version number specified by the previous field (testmode.version)
  ## Note: mention the major version number
  ## eg. enter 0.7.4 if u wish to provide an upgrade path from pravega 0.7.4 to 0.8.3
  fromVersion: ""

webhookCert:
  crt:
  key:
  ## Whether to generate the certificate or not.
  generate: false
  ## If false, the name of the pre-existing certificate needs to be provided.
  certName: selfsigned-cert-bk
  secretName: selfsigned-cert-tls-bk

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""

hooks:
  backoffLimit: 10
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/k8s-kubectl
    tag: v1.16.10
  ## Whether to create pre-delete hook which ensures that
  ## the operator cannot be deleted till the bookkeeper cluster
  ## custom resources have been cleaned up
  delete: true
