## Default values for pravega-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: pravega/bookkeeper-operator
  tag: 0.1.1
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: bookkeeper-operator

## Whether to create the CRD.
crd:
  create: true

## Whether to enable test mode.
testmode: false

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""
