## Default values for bookkeeper-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: pravega/bookkeeper-operator
  tag: 0.1.3
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: bookkeeper-operator

## Whether to create the CRD.
crd:
  create: true

testmode:
  enabled: false
  ## fromVersion is used to specify the
  ## test version of bookkeeper that you wish to deploy
  ## mention the major version number
  ## eg. enter 0.8.0 if u wish to deploy version 0.8.0-2500.efe501a
  fromVersion: ""
  ## toVersion is used to specify the
  ## test version of bookkeeper that you wish to provide an upgrade path to
  ## from the earlier specified version
  ## eg. enter 0.9.0 if u wish to provide an upgrade path from bookkeeper 0.8.0 to 0.9.0
  toVersion: ""

webhookCert:
  crt:
  key:
  ## Whether to generate the certificate or not.
  generate: false
  ## If false, the name of the pre-existing certificate needs to be provided.
  certName: selfsigned-cert-bk
  secretName: selfsigned-cert-tls-bk

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""

hooks:
  backoffLimit: 10
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
