apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "bookkeeper"
spec:
  version: 0.7.0
  zookeeperUri: zookeeper-client:2181
  image:
    repository: pravega/bookkeeper
    pullPolicy: IfNotPresent
  replicas: 3
  envVars: bookkeeper-configmap
  autoRecovery: true
  storage:
    ledgerVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
    journalVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
    indexVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
