apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: {{ template "bookkeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bookkeeper.commonLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  maxUnavailableBookkeeperReplicas: {{ .Values.maxUnavailableBookkeeperReplicas }}
  image:
    imageSpec:
      repository: {{ .Values.image.repository }}
      pullPolicy: {{ .Values.image.pullPolicy }}
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  envVars: {{ template "bookkeeper.fullname" . }}-configmap
  autoRecovery: {{ .Values.autoRecovery }}
  {{- if or (.Values.blockOwnerDeletion) (eq (.Values.blockOwnerDeletion | toString) "<nil>") }}
  blockOwnerDeletion: true
  {{- else }}
  blockOwnerDeletion: false
  {{- end }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  {{- if .Values.probes }}
  probes:
    {{- if .Values.probes.readiness }}
    readinessProbe:
      initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 20 }}
      periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
      failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 9 }}
      successThreshold: {{ .Values.probes.readiness.successThreshold | default 1 }}
      timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 5 }}
    {{- end }}
    {{- if .Values.probes.liveness }}
    livenessProbe:
      initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 60 }}
      periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 15 }}
      failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 4 }}
      successThreshold: {{ .Values.probes.liveness.successThreshold | default 1 }}
      timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 5 }}
    {{- end }}
  {{- end }}
  {{- if .Values.resources }}
  resources:
{{ toYaml .Values.resources | indent 6 }}
  {{- end }}
  storage:
    ledgerVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storage.ledger.className }}
      storageClassName: {{ .Values.storage.ledger.className }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.storage.ledger.volumeSize }}
    journalVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storage.journal.className }}
      storageClassName: {{ .Values.storage.journal.className }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.storage.journal.volumeSize }}
    indexVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.storage.index.className }}
      storageClassName: {{ .Values.storage.index.className }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.storage.index.volumeSize }}
  {{- if and .Values.jvmOptions (or .Values.jvmOptions.memoryOpts .Values.jvmOptions.gcOpts .Values.jvmOptions.gcLoggingOpts .Values.jvmOptions.extraOpts) }}
  jvmOptions:
    {{- if .Values.jvmOptions.memoryOpts }}
    memoryOpts:
{{ toYaml .Values.jvmOptions.memoryOpts | indent 6 }}
    {{- end }}
    {{- if .Values.jvmOptions.gcOpts }}
    gcOpts:
{{ toYaml .Values.jvmOptions.gcOpts | indent 6 }}
    {{- end }}
    {{- if .Values.jvmOptions.gcLoggingOpts }}
    gcLoggingOpts:
{{ toYaml .Values.jvmOptions.gcLoggingOpts | indent 6 }}
    {{- end }}
    {{- if .Values.jvmOptions.extraOpts }}
    extraOpts:
{{ toYaml .Values.jvmOptions.extraOpts | indent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.options }}
  options:
{{ toYaml .Values.options | indent 4 }}
  {{- end }}
